### ISSUE TITLE
[Enigma] Архитектура

### ISSUE THREAD

**Issue by pavel-b-novikov** [vavanrrrage/nsudotnet#1]
Краткость - сестра таланта, но видимо не ваша.
Если кратко - СЛИШКОМ много копипаста кода. Это архитектурная ошибка и так делать не надо.

Вы же видите что у вас декрипторы/енкрипторы почти идентичны по коду? Ну так и на кой сделали 6 (!) разных классов вместо вынесения процедуры чтения ключа в отдельную функцию? 

В общем сложите это все добро в меньшее количество классов.

Ну и конечно два раза повторяющийся свитч по алгоритмам в main-е порадовал, ага.
Давайте уже будем писать как студенты ФИТа, а не как студенты мехмата.

**Comment by vavanrrrage** [comment]
Ага, эпично тупанул, признаю. 
Вот касательно switch не совсем понятно: мне, получается, тогда сначала делать один switch по алгоритму шифрования, а уже внутри проверять encrypt/decrypt?

**Comment by pavel-b-novikov** [comment]
Слушайте, тут вариантов много чтобы обойтись одним свитчем. Я не могу так просто сходу сказать. Приудмайте сами.

**Comment by pavel-b-novikov** [comment]
Ну таки шо? Я по-прежнему вижу кучу классов, которые функциональность друг друга повторяют.

**Comment by vavanrrrage** [comment]
Исправлено.

**Comment by Biunovich** [comment]
>Давайте уже будем писать как студенты ФИТа, а не как студенты мехмата.

**Comment by pavel-b-novikov** [comment]
> streamWriter.Write(streamReader.ReadToEnd());

Ну што за...

**Comment by pavel-b-novikov** [comment]
StreamWriter/StreamReader в этом случае не прокатят. И расскажите мне почему.

**Comment by pavel-b-novikov** [comment]
> byte[] inputByteArray = new byte[fsInput.Length];
> fsInput.Read(inputByteArray, 0, inputByteArray.Length);
> cryptostream.Write(inputByteArray, 0, inputByteArray.Length);

Да что же вы творите-то, а... потоки вручную..

**Comment by vavanrrrage** [comment]
StreamReader и StreamWriter работают в определенной кодировке.
Исправлено.

**Comment by pavel-b-novikov** [comment]
У меня лицо от фейспалмов болит.
